version: '3.8'

services:
  gateway-service:
    build:
      context: ./services/gateway
    ports:
      - "8080:8080"
    depends_on:
      - frontend-service
      - osm-proxy-service
      - pathfinding-service
    restart: always

  frontend-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

  osm-proxy-service:
    build:
      context: ./services/osm-proxy
    restart: always
    environment:
      - PORT=3001

  pathfinding-service:
    build:
      context: ./services/pathfinding
    restart: always
